version: "3.7"

services:
  go-playlist:
    container_name: go-playlist
    image: ghcr.io/cubismod/go-playlist/go-playlist:latest
    labels:
    - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    volumes:
    - "./config.yaml:/app/config.yaml:ro"
    ports:
      - 8080:8080
    environment:
      - SPOTIFY_ID=<spotify_id>
      - SPOTIFY_SECRET=<spotify_secret>
      - HOSTNAME=http://localhost
      - PORT=8080
      - NTFY_PW=<go_ntfy_pw>
      - NTFY_URL=<go_ntfy_url>
    logging:
      driver: journald
      options:
        tag: 'go-playlist'
